name: Demo Workflow
on: 
  pull_request
  
jobs:
  Markdown-Linter:
     runs-on: ubunto_latest
    steps:
      - name: Check out code
        uses: action/checkout@v2
      - name: Markdown Linting Action
        uses: avto-dev/markdown-lint@v1.5.0
        with:
          args: '.'
          config: 'markdownlist.yml'
